config/routes.rb
Rails.application.routes.draw do
  resources :records, only: [:new, :create, :edit, :update]

  get "/create", to: "records#new"
  get "/record/:secret/:source_id(/:scanned_by)", to: "records#new"

  get "/qr_code", to: "qr_codes#show"
  get "/data", to: "data#index"
  get "/simulation", to: "data#simulation"
  get "/stickers", to: "data#stickers", as: :sticker
  post "/stickers/:record_id/take", to: "data#take_sticker", as: :take_sticker
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/record.rb
class Record < ApplicationRecord
  enum gender: [:prefer_not_to_say, :male, :female]
  enum age_range: [:"18_24", :"25_29", :"30_34", :"35_39", :"40_44", :"45_49", :"50_plus"]
  enum infection_location: [:lower_ground_floor, :ground_floor, :first_floor, :second_floor, :third_floor]

  scope :awaiting_stickers, -> { where.not(scanned_by: nil).where(stickers_taken: false).order(created_at: :desc) }
end

app/models/simulation.rb
require 'csv'

class Simulation
  def initialize(number_of_initial_cases: 10, number_of_stickers: 3)
    @people = {}
    @records = []
    @number_of_stickers = number_of_stickers
    @number_of_initial_cases = number_of_initial_cases
    number_of_initial_cases.times { |x| @people[x] = number_of_stickers }
    FakeRecord.reset(number_of_initial_cases)
  end

  def run(interaction_count: 150)
    @people_ballot = @people.keys.dup
    interaction_count.times do
      source = give_sticker
      new_record = FakeRecord.new(source)
      @records << new_record
      @people[new_record.id] = @number_of_stickers
    end
  end

  def data
    column_names = Record.column_names
    CSV.generate do |csv|
      csv << column_names
      @records.each do |record|
        csv << column_names.map { |c| record.send(c) }
      end
    end
  end

  private

  def give_sticker
    person = @people_ballot.sample
    stickers_left = @people[person]
    if stickers_left == 1
      @people.delete(person)
      @people_ballot.delete_if { |p| p == person }
    else
      @people[person] = stickers_left - 1
    end
    @people_ballot += @people.keys
    person
  end

  class FakeClock
    def self.now
      @now ||= Time.now
      @now += rand(60*3) + 30
    end
  end

  class FakeRecord
    attr_reader :id, :source_id, :gender, :age_range, :infection_location, :created_at, :updated_at

    def self.reset(next_id)
      @next_id = next_id
    end

    def self.next_id
      value = @next_id
      @next_id += 1
      value
    end

    def initialize(source_id)
      @source_id = source_id
      @gender = Record.genders.keys.sample
      @age_range = Record.age_ranges.keys.sample
      @infection_location = Record.infection_locations.keys.sample
      @created_at = @updated_at = FakeClock.now
      @id = FakeRecord.next_id
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/data_controller.rb
require 'csv'

class DataController < ApplicationController
  def index
    column_names = Record.column_names
    csv_data = CSV.generate do |csv|
      csv << column_names
      source = Record
      if params[:latest_id].present?
        source = source.where("id > ?", params[:latest_id])
      end
      source.find_each do |record|
        csv << record.attributes.values_at(*column_names)
      end
    end
    send_data csv_data, filename: 'epidemo.csv'
  end

  def simulation
    sim_params = {
      number_of_initial_cases: params.fetch(:number_of_initial_cases, 10).to_i,
      number_of_stickers: params.fetch(:number_of_stickers, 3).to_i
    }
    s = Simulation.new(sim_params)
    Random.srand(params.fetch(:seed, 123456).to_i)
    s.run(interaction_count: [10000, params.fetch(:number_of_iterations, 1000).to_i].min)
    send_data s.data, filename: 'epidemo-simulation.csv'
  end

  def stickers
    @records = Record.awaiting_stickers
  end

  def take_sticker
    @record = Record.find(params[:record_id])
    @record.update_attributes(stickers_taken: true)
    redirect_to sticker_path
  end
end

app/controllers/qr_codes_controller.rb
class QrCodesController < ApplicationController
  def show
    @qr = RQRCode::QRCode.new(params[:source_id])
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_filter :check_secret

  def new
    @record = Record.new(record_attributes)
  end

  def create
    @record = Record.new(record_attributes)
    if @record.save
      redirect_to edit_record_path(@record, secret: Rails.application.secrets.http_password)
    else
      render text: "There's been an error creating this record"
    end
  end

  def edit
    @record = Record.find(params[:id])
  end

  def update
    @record = Record.find(params[:id])
    if @record.update_attributes(record_attributes)
      flash.now[:notice] = "Record updated"
    else
      flash.now[:alert] = "There was a problem updating this record"
    end
    render action: :edit
  end

  private

  def check_secret
    raise "NO" unless params[:secret] == Rails.application.secrets.http_password
  end

  def record_attributes
    if params[:record]
      params.require(:record).permit(:source_id, :gender, :age_range, :infection_location, :scanned_by)
    elsif params[:scanned_by]
      params.permit(:source_id, :scanned_by)
    else
      raise "Malformed params: #{params}"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/data/stickers.html.erb
<% content_for :meta do %>
  <% unless params[:no] %>
    <meta http-equiv="refresh" content="5;URL='<%= sticker_url %>'" />
  <% end %>
<% end %>
<div class="row">
  <div class="col-xs-12">
    <table class="table table-striped">
      <% @records.each do |record| %>
        <tr>
          <td>
            <%= form_tag take_sticker_path(record_id: record.to_param), class: "form-inline" do %>
              <div class="form-group">
                <%= submit_tag "Take", class: "btn btn-lg btn-default btn-block" %>
              </div>
            <% end %>
          </td>
          <td>
            <h1>Sticker set <strong><%= record.id %></strong> to <%= record.scanned_by %></h1>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Epidemo</title>
    <%= csrf_meta_tags %>
    <%= yield :meta %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <% if text = flash[:notice] %>
        <div class="alert alert-info" role="alert"><%= text %></div>
      <% end %>
      <% if text = flash[:alert] %>
        <div class="alert alert-danger" role="alert"><%= text %></div>
      <% end %>
    </div>
        
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/qr_codes/show.html.erb
<style type="text/css">
 table {
  border-width: 0;
  border-style: none;
  border-color: #0000ff;
  border-collapse: collapse;
 }
 td {
   border-width: 0;
   border-style: none;
   border-color: #0000ff;
   border-collapse: collapse;
   padding: 0;
   margin: 0;
   width: 10px;
   height: 10px;
 }
 td.black { background-color: #000; }
 td.white { background-color: #fff; }
</style>
 
<div class="row">
  <div class="col-sm-12">
    <p>QR code for <%= params[:source_id] %></p>
    <table>
     <% @qr.modules.each_index do |x| -%>
       <tr>
       <% @qr.modules.each_index do |y| -%>
        <% if @qr.dark?(x,y) -%>
        <td class="black"/>
        <% else -%>
        <td class="white"/>
        <% end -%>
       <% end -%>
       </tr>
     <% end -%>
    </table>
  </div>
</div>

app/views/records/create.html.erb
<div class="row">
  <div class="col-sm-12">
    <%= bootstrap_form_for @record do |f| %>
      <div class="form-group">
        <label class="control-label">New case number</label>
        <h1><%= @record.id %></h1>
      </div>
      <%= f.hidden_field :source_id %>
      <%= f.select :gender, Record.genders.keys.map { |k| [k.humanize, k] } %>
      <%= f.select :age_range, Record.age_ranges.keys.map { |k| [k.gsub('_plus', '+').gsub('_', ' to '), k] } %>
      <%= f.select :infection_location, Record.infection_locations.keys.map { |k| [k.humanize, k] } %>      
      <%= hidden_field_tag :secret, Rails.application.secrets.http_password %>
      <%= f.primary %>
    <% end %>

app/views/records/edit.html.erb
<div class="row">
  <div class="col-sm-12">
    <%= bootstrap_form_for @record do |f| %>
      <div class="form-group">
        <label class="control-label">New case number</label>
        <h1><%= @record.id %></h1>
      </div>
      <%= f.hidden_field :source_id %>
      <%= f.hidden_field :scanned_by %>
      <fieldset>
        <label>Gender</label><br>
        <div class="btn-group" data-toggle="buttons">
          <% Record.genders.keys.each.with_index do |gender, i| %>
            <% selected = f.object.gender.nil? ? i==0 : f.object.gender == gender %>
            <label class="btn btn-primary <%= 'active' if selected %>">
              <input type="radio" name="record[gender]" value="<%= gender %>" id="record_gender_<%= gender %>" autocomplete="off" <% 'checked' if selected %>> <%= gender.to_s.humanize %>
            </label>
          <% end %>
        </div>
      </fieldset>
      <fieldset>
        <label>Age range</label><br>
        <div class="btn-group" data-toggle="buttons">
          <% Record.age_ranges.keys.each.with_index do |age_range, i| %>
            <% selected = f.object.age_range.nil? ? i==0 : f.object.age_range == age_range %>
            <label class="btn btn-primary <%= 'active' if selected %>">
              <input type="radio" name="record[age_range]" value="<%= age_range %>" id="record_age_range_<%= age_range %>" autocomplete="off" <% 'checked' if selected %>> <%= age_range.to_s.gsub('_plus', '+').gsub('_', ' to ').humanize %>
            </label>
          <% end %>
        </div>
      </fieldset>
      <fieldset>
        <label>Infection location</label><br>
        <div class="btn-group" data-toggle="buttons">
          <% Record.infection_locations.keys.each.with_index do |infection_location, i| %>
            <% selected = f.object.infection_location.nil? ? i==0 : f.object.infection_location == infection_location %>
            <label class="btn btn-primary <%= 'active' if selected %>">
              <input type="radio" name="record[infection_location]" value="<%= infection_location %>" id="record_infection_location_<%= infection_location %>" autocomplete="off" <% 'checked' if selected %>> <%= infection_location.to_s.humanize %>
            </label>
          <% end %>
        </div>
      </fieldset>
      <p></p>
      <p></p>
      <%# <%= f.select :gender, Record.genders.keys.map { |k| [k.humanize, k] } %1> %>
      <%# <%= f.select :age_range, Record.age_ranges.keys.map { |k| [k.gsub('_plus', '+').gsub('_', ' to '), k] } %1> %>
      <%# <%= f.select :infection_location, Record.infection_locations.keys.map { |k| [k.humanize, k] } %1> %>      
      <%= hidden_field_tag :secret, Rails.application.secrets.http_password %>
      <%= f.primary "Update case", class: 'btn btn-primary btn-lg btn-block' %>
      <p></p>
      <p>Thanks!</p>
    <% end %>
  </div>
</div>

app/views/records/new.html.erb
<div class="row">
  <div class="col-xs-12" style="text-align: center; margin-top: 10px;">
    <%= bootstrap_form_for @record do |f| %>
      <%= f.hidden_field :source_id %>
      <%= f.hidden_field :scanned_by %>
      <%= hidden_field_tag :secret, Rails.application.secrets.http_password %>
      <p>You have scanned case #<%= @record.source_id %></p>
      <%= f.primary "Create new case", class: 'btn btn-primary btn-lg btn-block' %>
    <% end %>
  </div>
</div>